CREATE TABLE IF NOT EXISTS item (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(40),
item_status VARCHAR (30) NOT NULL);

CREATE TABLE IF NOT EXISTS audit_item (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
item_id BIGINT UNSIGNED NOT NULL,
date DATETIME, action VARCHAR (30) NOT NULL,
FOREIGN KEY (item_id) REFERENCES item (id));