CREATE TABLE IF NOT EXISTS item (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(40), itemStatus VARCHAR (30) NOT NULL);
CREATE TABLE IF NOT EXISTS audit_item (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, date DATETIME, action VARCHAR (30) NOT NULL);
ALTER TABLE audit_item ADD item_id BIGINT UNSIGNED NOT NULL, ADD FOREIGN KEY (item_id) REFERENCES item (id);